runtime: python
env: flex

api_version: 1
threadsafe: true
service: pymodule

runtime_config:
  python_version: 3
  document_root: python

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

#handlers:
#- url: /hello.*
#  script: hello.app

#- url: /.*
#  script: main.app
#login: admin
#secure: always

