#runtime: python27

#api_version: 1
#service: pymodule
#threadsafe: true

#manual_scaling:
#  instances: 1

#resources:
#  cpu: 1
#  memory_gb: 2
#  disk_size_gb: 10

#handlers:
#  - url: /python/.*
#    script: main.app

#libraries:
#- name: webapp2
#  version: "2.5.2"
