runtime: python27
#env: flex
api_version: 1
threadsafe: true
service: pymodule

runtime_config:
  document_root: python

handlers:
- url: /hello.*
  script: hello.app

- url: /.*
  script: main.app
  #login: admin
  #secure: always

#handlers:
#- url: /hello.*
#  script: hello.app

#- url: /.*
#  script: main.app
#login: admin
#secure: always

